package cast

import (
	"testing"
)

func TestAsBool(t *testing.T) {
	str := "true"
	var nilPtr *bool
	tests := []castTest[bool]{
		{nil, false, ""},
		{true, true, ""},
		{false, false, ""},
		{uint(1), true, ""},
		{uint(0), false, ""},
		{int(1), true, ""},
		{int(0), false, ""},
		{int8(1), true, ""},
		{int8(0), false, ""},
		{uint8(1), true, ""},
		{uint8(0), false, ""},
		{int16(1), true, ""},
		{int16(0), false, ""},
		{uint16(1), true, ""},
		{uint16(0), false, ""},
		{int32(1), true, ""},
		{int32(0), false, ""},
		{uint32(1), true, ""},
		{uint32(0), false, ""},
		{int64(1), true, ""},
		{int64(0), false, ""},
		{uint64(1), true, ""},
		{uint64(0), false, ""},
		{float32(0), false, ""},
		{float32(1), true, ""},
		{float64(0), false, ""},
		{float64(1), true, ""},
		{"true", true, ""},
		{"false", false, ""},
		{&str, true, ""},
		{nilPtr, false, ""},
		{customAny(nil), false, ""},
		{customBool(true), true, ""},
		{customBool(false), false, ""},
		{customUint(1), true, ""},
		{customUint(0), false, ""},
		{customInt(1), true, ""},
		{customInt(0), false, ""},
		{customInt8(1), true, ""},
		{customInt8(0), false, ""},
		{customUint8(1), true, ""},
		{customUint8(0), false, ""},
		{customInt16(1), true, ""},
		{customInt16(0), false, ""},
		{customUint16(1), true, ""},
		{customUint16(0), false, ""},
		{customInt32(1), true, ""},
		{customInt32(0), false, ""},
		{customUint32(1), true, ""},
		{customUint32(0), false, ""},
		{customInt64(1), true, ""},
		{customInt64(0), false, ""},
		{customUint64(1), true, ""},
		{customUint64(0), false, ""},
		{customFloat32(0), false, ""},
		{customFloat32(1), true, ""},
		{customFloat64(0), false, ""},
		{customFloat64(1), true, ""},
		{customString("true"), true, ""},
		{customString("false"), false, ""},
		{"foo", false, "failed to cast string to bool"},
		{struct{}{}, false, "failed to cast struct {} to bool"},
	}
	runCastTests(t, "AsBool", AsBool, tests)
}
